### ISSUE TITLE
Change auto-generated code message to comply with Go's convention.

### ISSUE THREAD

**Issue by nlhepler** [martian-lang/martian-rust#53]
From the review comments by @adam-azarchs of another PR:
> [...] Go has established a convention for autogenerated files which is recognized by several tools such as vscode, and perhaps more crucially GitHub's PR viewer, to have a comment matching the regular expression `^// Code generated .* DO NOT EDIT\.$`. We should probably update martian-rust to match that convention.

**Comment by adam-azarchs** [comment]
#52

**Comment by adam-azarchs** [comment]
There's also a couple other issues there which should get addressed:
1. The copyright date.  Not sure what the best answer there is; using today's date would be bad, as it means every new-year's day we'd break every CI that checked for up-to-date mro files.
2. This repo shouldn't be hard-coding the copyright owner to 10X Genomics.

Probably the right answer there would be to make the copyright header string something that was configured, either via a command-line option or something in the rust source code.
